<FirstScreen>:
    GridLayout:
        cols: 1
        padding: 10
        spacing: 10
        Image:
            id: img
            size_hint_y: 0.7
        TextInput:
            id: user_query
            size_hint_y: 0.15
        Button:
            size_hint_y: 0.15
            text: 'Search Image'
            on_press: root.search_image()

<RootWidget>:
    FirstScreen:
        id : first_screen
        name : 'first_screen'